### ISSUE TITLE
Thumbnails Path Broken

### ISSUE THREAD

**Issue by tiagovalenca** [trackit/trackflix-client#16]
The issue is on the StrapiApi.ts file, on the strapiMediaToThumbnail function, on the following const to be precise:
 ```
const thumbnailFormated = {
                 id: `${thumbnailObj.id}`,
                 ext: thumbnail.ext,
                 src: `${this.baseUrl}${thumbnail.url}`,
                 createdAt,
                 updatedAt,
 }
```

What is happening is the old thumbnails were on a folder called uploads for which the url is the same as the rest of the API, but the new ones (when added directly through the CMS) don’t use the same baseUrl. So, this snippet `${this.baseUrl}${thumbnail.url}`  is working for the old ones, but breaking the path for the new ones.

**Comment by nathandebalthasar** [comment]
Fixed by [fix(thumbnails): use correct thumbnail url](https://github.com/trackit/trackflix-client/commit/aa74bbd845dc4138e32c8084fa6a7b93828f12da). In the future we may want to migrate all assets to s3.
